<?xml version="1.0" encoding="utf-8"?><Database Name="ManOnTheMoonDB" Class="DataBaseModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\ManOnTheMoonDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ManOnTheMoonDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Upc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Length" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Retail_Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Sale_Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stock_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sub_Category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="On_Sale_Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Product_Product_Image" Member="Product_Images" ThisKey="Id" OtherKey="Product_Id" Type="Product_Image" />
      <Association Name="Brand_Product" Member="Brand1" ThisKey="Brand" OtherKey="Name" Type="Brand" IsForeignKey="true" />
      <Association Name="Category_Product" Member="Category1" ThisKey="Category" OtherKey="Name" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Brands" Member="Brands">
    <Type Name="Brand">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Brand_Product" Member="Products" ThisKey="Name" OtherKey="Brand" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Images" Member="Product_Images">
    <Type Name="Product_Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product_Image_1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Product_Image_2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Product_Image_3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Product_Product_Image" Member="Product" ThisKey="Product_Id" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Category_Image_Url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="Name" OtherKey="Category" Type="Product" />
    </Type>
  </Table>
</Database>